name: CI
on:
  push:
  pull_request:
  schedule:
  - cron: '0 1 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
      with:
        java-version: ${{matrix.java}}
        distribution: adopt
    - run: sbt -v
           "project precompiler"
           "+ test"
           "+ publishLocal"
           "project plugin"
           "^ publishLocal"
           "^ scripted"
    - name: check scalariform
      run: git diff --exit-code
    - run: rm -rf ~/.ivy2/local
